name: "sbt"

on:
  push:
    # run CI on any commit or PR
    # branches:
  pull_request:

jobs:
  sbt:
    name: "sbt"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SBT test
        id: sbt
        uses: lokkju/github-action-sbt@8-1.3.0-2.12.10
        with:
          commands: test
          sbt_project_directory: .
